---
title: "Welcome to Data Viz CPS Team Website!"
page-layout: article
format:
  html:
    toc: true
    toc-location: right
    code-tools: false
    fig-align: center
    
execute:
  #enabled: false
  freeze: auto
---

------------------------------------------------------------------------

## About Our Project

We are looking at the different labor market patterns during the Covid-19 time using the CPS dataset. Our primary focus is on impact of COVID-19 on United States Veteran Unemployment, but we are also exmaining additional intersectionality such as household type, educational background and other demographic information.

------------------------------------------------------------------------

## U.S. Government Current Population Survey (CPS)

[Current Population Survey](https://www.census.gov/data/datasets/time-series/demo/cps/cps-basic.html), commonly referred to as the CPS, is conducted jointly by two major U.S. government agencies, the U.S. Census Bureau and the Bureau of Labor Statistics, or BLS.

The CPS is a monthly household survey designed to measure key aspects of the labor market and demographic information.

For each month, it collects data from around 60,000 households, representing millions of individuals nationwide. The dataset covers a wide range of variables as well, including employment and unemployment status, income, educational background, household structures, and other demographic characteristics. Because of this rich demographic variables, the CPS is one of the few datasets that allow researchers to examine not only broad labor market trends, but also the distributional impacts on different diverse groups.

It has also maintained a consistent survey design since the 1940s, which allows researchers to make meaningful comparisons over time and track how labor markets respond to major events and economic recession for example Covid-19 which is the main focus of our group

------------------------------------------------------------------------

## Our Data Analysis Focus

Our project focuses on understanding the impact of major events on unemployment recovery, with an emphasis on identifying who recovered and why. The analysis seeks to capture how factors such as economic resilience, social structure, and individual resources shaped different recovery experiences.

#### Covid-19 Pandemic

The analysis centers on the Covid-19 pandemic period and the subsequent recovery phase, capturing how unemployment trends evolved as the economy reopened. This timeline allows for comparison between the height of pandemic-related job losses and the gradual return to employment, providing insights into long-term recovery and disparities that persisted beyond the immediate crisis.

#### Variables

[Overall CPS variables dictionary](https://www2.census.gov/programs-surveys/cps/datasets/2025/basic/2025_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt)

The Current population survey household data contains a wide range of variables, and to further explore these dynamics, several key variables from the data were selected:

-   ptdtrace – Race

-   peeduca – Highest Education Background

-   prtgage – Age

-   pelaydur – Unemployment Duration (in weeks)

-   hrhtype – Household Type

-   peafever – Veteran Status

These variables together capture demographic, socioeconomic, and structural characteristics that influence how individuals and communities experienced unemployment recovery during and after the pandemic.
